/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import Models.Supplier;
import BackCom.HTTP;
import java.io.IOException;


/**
 * @author juanrmz
 */
public class AddSupplier extends javax.swing.JFrame {

    /**
     * Creates new form AddSupplier
     */
    public AddSupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supplierName = new javax.swing.JTextField();
        supplierLName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        latitud = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        longitud = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        areaCode = new javax.swing.JTextField();
        supplierPhone = new javax.swing.JTextField();
        checkBoxMango = new javax.swing.JCheckBox();
        checkBoxFresa = new javax.swing.JCheckBox();
        checkBoxPina = new javax.swing.JCheckBox();
        checkBoxSandia = new javax.swing.JCheckBox();
        checkBoxLimon = new javax.swing.JCheckBox();
        checkBoxNaranja = new javax.swing.JCheckBox();
        checkBoxMelon = new javax.swing.JCheckBox();
        checkBoxUva = new javax.swing.JCheckBox();
        checkBoxMan = new javax.swing.JCheckBox();
        checkBoxManzana = new javax.swing.JCheckBox();
        checkBoxToronja = new javax.swing.JCheckBox();
        checkBoxAguac = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        checkBoxOtro = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Añadir Proveedor");
        setBackground(new java.awt.Color(153, 204, 255));
        setResizable(false);

        jLabel1.setText("Nombre(s)");

        jLabel2.setText("Apellidos");

        latitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latitudActionPerformed(evt);
            }
        });

        jLabel3.setText("Lat.");

        jLabel4.setText("Long.");

        jLabel5.setText("Tel.");

        areaCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaCodeActionPerformed(evt);
            }
        });

        checkBoxMango.setText("Mango");

        checkBoxFresa.setText("Fresa");
        checkBoxFresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxFresaActionPerformed(evt);
            }
        });

        checkBoxPina.setText("Piña");

        checkBoxSandia.setText("Sandía");

        checkBoxLimon.setText("Limón");
        checkBoxLimon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxLimonActionPerformed(evt);
            }
        });

        checkBoxNaranja.setText("Naranja");
        checkBoxNaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxNaranjaActionPerformed(evt);
            }
        });

        checkBoxMelon.setText("Melón");
        checkBoxMelon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMelonActionPerformed(evt);
            }
        });

        checkBoxUva.setText("Uva");
        checkBoxUva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxUvaActionPerformed(evt);
            }
        });

        checkBoxMan.setText("Mandarina");

        checkBoxManzana.setText("Manzana");

        checkBoxToronja.setText("Toronjas");

        checkBoxAguac.setText("Aguacate");
        checkBoxAguac.setToolTipText("");

        checkBoxOtro.setText("Otro(s)");

        jButton1.setText("Añadir Proveedor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(checkBoxOtro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkBoxSandia)
                                        .addComponent(checkBoxMango))
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkBoxFresa)
                                        .addComponent(checkBoxLimon))
                                    .addGap(22, 22, 22)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkBoxNaranja)
                                        .addComponent(checkBoxPina)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkBoxManzana)
                                        .addComponent(checkBoxMelon))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(checkBoxUva)
                                            .addGap(38, 38, 38)
                                            .addComponent(checkBoxMan))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(checkBoxToronja)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(checkBoxAguac))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(areaCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(supplierLName)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(latitud, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(longitud))
                                            .addComponent(supplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(latitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(areaCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxMango)
                    .addComponent(checkBoxFresa)
                    .addComponent(checkBoxPina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxSandia)
                    .addComponent(checkBoxLimon)
                    .addComponent(checkBoxNaranja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxMelon)
                    .addComponent(checkBoxUva)
                    .addComponent(checkBoxMan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxManzana)
                    .addComponent(checkBoxToronja)
                    .addComponent(checkBoxAguac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxOtro)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void latitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latitudActionPerformed

    private void areaCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaCodeActionPerformed

    private void checkBoxFresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxFresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxFresaActionPerformed

    private void checkBoxLimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxLimonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxLimonActionPerformed

    private void checkBoxMelonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMelonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxMelonActionPerformed

    private void checkBoxUvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxUvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxUvaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkBoxNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxNaranjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxNaranjaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSupplier().setVisible(true);
            }
        });
        
        HTTP test = new HTTP("Hola");
        Supplier[] supplierList = test.get("https://fruitappapi.azurewebsites.net/API/providers");
        System.out.println(supplierList[0].getId());
        
        Supplier testSupplier =  new Supplier("Juan", "Ramírez",new String[] {"Naranja" , "Melón"}, new String[] {"USDA" , "MEX"});
        test.post(testSupplier, "https://fruitappapi.azurewebsites.net/API/providers");
    }
    
    public javax.swing.JCheckBox[] fruits; 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaCode;
    private javax.swing.JCheckBox checkBoxAguac;
    private javax.swing.JCheckBox checkBoxFresa;
    private javax.swing.JCheckBox checkBoxLimon;
    private javax.swing.JCheckBox checkBoxMan;
    private javax.swing.JCheckBox checkBoxMango;
    private javax.swing.JCheckBox checkBoxManzana;
    private javax.swing.JCheckBox checkBoxMelon;
    private javax.swing.JCheckBox checkBoxNaranja;
    private javax.swing.JCheckBox checkBoxOtro;
    private javax.swing.JCheckBox checkBoxPina;
    private javax.swing.JCheckBox checkBoxSandia;
    private javax.swing.JCheckBox checkBoxToronja;
    private javax.swing.JCheckBox checkBoxUva;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField latitud;
    private javax.swing.JTextField longitud;
    private javax.swing.JTextField supplierLName;
    private javax.swing.JTextField supplierName;
    private javax.swing.JTextField supplierPhone;
    // End of variables declaration//GEN-END:variables
}
