/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import BackCom.HTTP;
import Models.Supplier;
import java.io.IOException;

/**
 *
 * @author spide
 */
public class EditSupplier extends javax.swing.JPanel {
    Supplier supplier;
    HTTP test;
    ShowSuppliers showSuppliers;
    /**
     * Creates new form EditSupplier
     */
    public EditSupplier(Supplier s, ShowSuppliers ss) {
        initComponents();
        test = new HTTP("hola");
        supplier = s;
        showSuppliers = ss;
        setTextFields();
        this.repaint();
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEvent(evt);
            }
        });
                
    }
    private void sendEvent(java.awt.event.ActionEvent evt){
        supplier.setLName(supplierLName.getText());
        supplier.setLat(Float.parseFloat(latitud.getText()));
        supplier.setLon(Float.parseFloat(longitud.getText()));
        supplier.setName(supplierName.getText());
        supplier.setMName("");
        supplier.setPhone(areaCode.getText() + " " + supplierPhone.getText());
       

        try{
            test.put(supplier, "http://fruitappapi.azurewebsites.net/API/providers");
        } catch (IOException e){
            System.out.println(e); 
        }
        showSuppliers.showAllSuppliers();
    }
    private void setTextFields(){
        supplierName.setText(supplier.getName()+supplier.getMName());
        supplierLName.setText(supplier.getLName());
        
        latitud.setText(""+supplier.getLat());
        longitud.setText(""+supplier.getLon());
        areaCode.setText(supplier.getPhone().substring(0,3));
        supplierPhone.setText(supplier.getPhone().substring(3));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBL_name = new javax.swing.JLabel();
        supplierName = new javax.swing.JTextField();
        LBL_lName = new javax.swing.JLabel();
        supplierLName = new javax.swing.JTextField();
        LBL_lat = new javax.swing.JLabel();
        latitud = new javax.swing.JTextField();
        LBL_long = new javax.swing.JLabel();
        longitud = new javax.swing.JTextField();
        LBL_tel = new javax.swing.JLabel();
        areaCode = new javax.swing.JTextField();
        supplierPhone = new javax.swing.JTextField();
        send = new javax.swing.JButton();

        LBL_name.setText("Nombre(s)");

        LBL_lName.setText("Apellidos");

        LBL_lat.setText("Lat.");

        latitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latitudActionPerformed(evt);
            }
        });

        LBL_long.setText("Long.");

        LBL_tel.setText("Tel.");

        areaCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaCodeActionPerformed(evt);
            }
        });

        send.setText("Aceptar");
        send.setActionCommand("Aceptar");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LBL_name)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LBL_lat)
                                .addComponent(LBL_lName)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LBL_tel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(areaCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(supplierLName)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(latitud, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBL_long)
                                    .addGap(18, 18, 18)
                                    .addComponent(longitud))
                                .addComponent(supplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(73, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(send)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LBL_name))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(supplierLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LBL_lName))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(latitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LBL_lat)
                        .addComponent(LBL_long)
                        .addComponent(longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LBL_tel)
                        .addComponent(areaCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(supplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(80, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void latitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latitudActionPerformed

    private void areaCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaCodeActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_sendActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL_lName;
    private javax.swing.JLabel LBL_lat;
    private javax.swing.JLabel LBL_long;
    private javax.swing.JLabel LBL_name;
    private javax.swing.JLabel LBL_tel;
    private javax.swing.JTextField areaCode;
    private javax.swing.JTextField latitud;
    private javax.swing.JTextField longitud;
    private javax.swing.JButton send;
    private javax.swing.JTextField supplierLName;
    private javax.swing.JTextField supplierName;
    private javax.swing.JTextField supplierPhone;
    // End of variables declaration//GEN-END:variables
}
