/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;
import java.awt.*;
//import App.EditOrder;
import Models.Order;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JDialog;
/**
 *
 * @author bvlul
 */
public class OrderLabel extends javax.swing.JPanel {
    Order order;
    ShowOrders showOrders;
    JDialog dial;
    public OrderLabel(Order x, ShowOrders y){
        initComponents();
        order = x;
        showOrders = y;
        this.lbID.setText(order.getOrderId());
        this.lbFruit.setText(order.getName());
        
        this.lbQty.setText("" + order.getQuantity());
        
        this.lbPending.setText("" + order.getPendingQty());
        
        this.setVisible(true);
        this.setBackground(new Color(245,245,245));
        this.repaint();
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbFruit = new javax.swing.JLabel();
        lbQty = new javax.swing.JLabel();
        pos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbPending = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel1.setText("No. Orden:");

        jLabel2.setText("Fruta:");

        lbFruit.setText("jLabel3");

        lbQty.setText("jLabel3");

        pos.setText("Cantidad:");

        jLabel4.setText("Cant. Pendiente:");

        lbPending.setText("jLabel5");

        lbID.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(68, 68, 68)
                        .addComponent(lbID)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(pos)
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPending)
                            .addComponent(lbQty)
                            .addComponent(lbFruit))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFruit)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos)
                    .addComponent(lbQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbPending))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbFruit;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbPending;
    private javax.swing.JLabel lbQty;
    private javax.swing.JLabel pos;
    // End of variables declaration//GEN-END:variables


}
