/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import BackCom.HTTP;
import Models.Supplier;
import java.awt.GridLayout;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;

/**
 *
 * @author spide
 */
public class ShowSuppliers extends javax.swing.JPanel {
    HTTP test;
    Supplier[] suppliers;
    /**
     * Creates new form ShowSuppliers
     */
    public ShowSuppliers() {
        initComponents();
        test = new HTTP("hola");
        try{
            suppliers = test.getSupplier("http://fruitappapi.azurewebsites.net/API/providers");
            
        }catch(Exception e){
            System.out.println(e);
        }
        showAllSuppliers();
    }
    public void showAllSuppliers(){
        javax.swing.JPanel sup, panel;
        panel = new javax.swing.JPanel();
        panel.setVisible(true);
        panel.setLayout(new GridLayout(0,1));
        suppScroll.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);
        for(Supplier s: suppliers){
            sup = new SupplierLabel(s, this);
            panel.add(sup);
        }
        panel.repaint();
        //jScrollPane1.setBorder(null);
        suppScroll.getViewport().setView(panel);
        suppScroll.setVisible(true);
        suppScroll.repaint();
    }
     public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowOrders().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        suppScroll = new javax.swing.JScrollPane();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Proveedores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suppScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suppScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane suppScroll;
    // End of variables declaration//GEN-END:variables
}
